// vueTodoApp/src/components/TodoList.vue
<template>
  <Observer>
    <div class="todo-list" v-if="store.list.length > 0">
      <div v-for="todo in store.list" :key="todo.id" class="todo">
        <TodoItem :data="todo" />
      </div>
    </div>
  </Observer>
</template>

<script>
import { Observer } from 'mobx-vue-lite';

import TodoItem from './TodoItem.vue';

export default {
  name: 'TodoList',
  components: {
    Observer,
    TodoItem,
  },
  inject: ['store'],
};
</script>

// reactTodoApp/src/components/TodoList.jsx
import React, { useContext } from 'react';
import { observer } from 'mobx-react';

import { AppContext } from '../App';
import TodoItem from './TodoItem.jsx';

const TodoList = () => {
  const store = useContext(AppContext);

  return (
    <>
      {store.list.length > 0 && (
        <div className="todo-list">
          {store.list.map((item) => (
            <TodoItem key={item.id} data={item} />
          ))}
        </div>
      )}
    </>
  );
};

export default observer(TodoList);
