// vueTodoApp/src/components/TodoItem.vue
<template>
  <div class="todo-item">
    <div class="content" @click="handleToggle">
      <p v-bind:class="{ 'is-done': data.isDone }">
        {{ data.content }}
      </p>
    </div>
    <button type="button" @click="handleDelete">Delete</button>
  </div>
</template>

<script>
import { store } from 'redux-todo-core';
import { deleteItem, toggleItem } from 'redux-todo-core/todoSlice';

export default {
  name: 'TodoItem',
  props: {
    data: Object,
  },
  methods: {
    handleToggle() {
      store.dispatch(toggleItem(this.data.id));
    },
    handleDelete() {
      store.dispatch(deleteItem(this.data.id));
    },
  },
};
</script>

// reactTodoApp/src/components/TodoItem.jsx
import React from 'react';
import { useDispatch } from 'react-redux';

import { toggleItem, deleteItem } from 'redux-todo-core/todoSlice';

const TodoItem = ({ data }) => {
  const dispatch = useDispatch();

  const handleToggle = () => {
    dispatch(toggleItem(data.id));
  };

  const handleDelete = () => {
    dispatch(deleteItem(data.id));
  };

  return (
    <div className="todo-item">
      <div className="content" onClick={handleToggle}>
        <p className={data.isDone ? 'is-done' : ''}>{data.content}</p>
      </div>
      <button onClick={handleDelete}>Delete</button>
    </div>
  );
};

export default TodoItem;
