// vueTodoApp/src/components/TodoList.vue
<template>
  <div v-if="loading">loading..</div>
  <div class="todo-list" v-if="todoList.length > 0">
    <div v-for="todo in todoList" :key="todo.id" class="todo">
      <TodoItem :data="todo" />
    </div>
  </div>
</template>

<script>
import { store } from 'redux-todo-core';
import { fetchTodoList } from 'redux-todo-core/todoSlice';

import TodoItem from './TodoItem.vue';

export default {
  name: 'TodoList',
  components: {
    TodoItem,
  },
  data() {
    return {
      loading: false,
      todoList: [],
    };
  },
  created: function () {
    const { loading, list } = store.getState().todo;
    this.loading = loading;
    this.todoList = list;

    store.subscribe(() => {
      const { loading, list } = store.getState().todo;
      this.loading = loading;
      this.todoList = list;
    });
  },
  mounted() {
    store.dispatch(fetchTodoList());
  },
};
</script>

// todoApp/ui/reactTodoApp/src/components/TodoList.jsx
import React, { useEffect } from 'react';
import { useSelector, useDispatch } from 'react-redux';

import { fetchTodoList } from 'redux-todo-core/todoSlice';

import TodoItem from './TodoItem.jsx';

const TodoList = () => {
  const dispatch = useDispatch();

  const list = useSelector((state) => state.todo.list);
  const loading = useSelector((state) => state.todo.loading);

  useEffect(() => {
    console.log('fetch')
    dispatch(fetchTodoList('test'));
  }, []);

  return (
    <>
      {loading && 'loading..'}
      {list.length > 0 && (
        <div className="todo-list">
          {list.map((item) => (
            <TodoItem key={item.id} data={item} />
          ))}
        </div>
      )}
    </>
  );
};

export default TodoList;
