// vueTodoApp/src/components/AddBar.vue
<template>
  <form @submit="onSubmit" class="add-bar">
    <input type="text" v-model="value" placeholder="Add Todo..." />
    <input type="submit" value="Submit" />
  </form>
</template>

<script>
import { store } from 'redux-todo-core';
import { addItem } from 'redux-todo-core/todoSlice';

export default {
  name: 'AddBar',
  data() {
    return {
      value: '',
    };
  },
  methods: {
    onSubmit(e) {
      e.preventDefault();
      store.dispatch(addItem(this.value));
      this.value = '';
    },
  },
};
</script>

// todoApp/ui/reactTodoApp2/src/components/AddBar.jsx
import React, { useState } from 'react';
import { useDispatch } from 'react-redux';

import { addItem } from 'redux-todo-core/todoSlice';

const AddBar = () => {
  const dispatch = useDispatch();

  const [value, setvalue] = useState('');

  const handleChange = (event) => {
    setvalue(event.target.value);
  };

  const handleAdd = () => {
    if (value) {
      dispatch(addItem(value));
      setvalue('');
    }
  };

  return (
    <div className="add-bar">
      <input
        type="text"
        value={value}
        placeholder="Add Todo..."
        onChange={handleChange}
      />
      <button type="button" onClick={handleAdd}>
        Add
      </button>
    </div>
  );
};

export default AddBar;
