// vueTodoApp/src/components/TodoItem.vue
<template>
  <div class="todo-item">
    <div class="title" @click="handleToggle">
      <p v-bind:class="{ 'is-completed': data.completed }">
        {{ data.title }}
      </p>
    </div>
    <button type="button" @click="handleDelete">Delete</button>
  </div>
</template>

<script>
import { store } from 'redux-todo-core';
import { deleteItem, toggleItem } from 'redux-todo-core/todoSlice';

export default {
  name: 'TodoItem',
  props: {
    data: Object,
  },
  methods: {
    handleToggle() {
      store.dispatch(toggleItem(this.data));
    },
    handleDelete() {
      store.dispatch(deleteItem(this.data.id));
    },
  },
};
</script>

// todoApp/ui/reactTodoApp2/src/components/TodoItem.jsx
import React from 'react';
import { useDispatch } from 'react-redux';

import { toggleItem, deleteItem } from 'redux-todo-core/todoSlice';

const TodoItem = ({ data }) => {
  const dispatch = useDispatch();

  const handleToggle = () => {
    dispatch(toggleItem(data));
  };

  const handleDelete = () => {
    dispatch(deleteItem(data.id));
  };

  return (
    <div className="todo-item">
      <div className="title" onClick={handleToggle}>
        <p className={data.completed ? 'is-completed' : ''}>{data.title}</p>
      </div>
      <button onClick={handleDelete}>Delete</button>
    </div>
  );
};

export default TodoItem;
