// todoApp/ui/vueTodoApp/src/components/TodoItem.vue
<template>
  <div class="todo-item">
    <div class="title" @click="handleToggle">
      <p v-bind:class="{ 'is-completed': data.completed }">
        {{ data.title }}
      </p>
    </div>
    <button type="button" @click="handleDelete">Delete</button>
  </div>
</template>

<script>
export default {
  name: 'TodoItem',
  props: {
    data: Object,
  },
  inject: ['store'],
  methods: {
    handleToggle() {
      this.store.toggleItem(this.data);
    },
    handleDelete() {
      this.store.deleteItem(this.data.id);
    },
  },
};
</script>

// todoApp/ui/reactTodoApp2/src/components/TodoItem.jsx
import React, { useContext } from 'react';

import { AppContext } from '../App';

const TodoItem = ({ data }) => {
  const store = useContext(AppContext);

  const handleToggle = () => {
    store.toggleItem(data);
  };

  const handleDelete = () => {
    store.deleteItem(data.id);
  };

  return (
    <div className="todo-item">
      <div className="title" onClick={handleToggle}>
        <p className={data.completed ? 'is-completed' : ''}>{data.title}</p>
      </div>
      <button onClick={handleDelete}>Delete</button>
    </div>
  );
};

export default TodoItem;
