// todoApp/ui/reactTodoApp2/src/components/TodoList.jsx
import React, { useContext, useEffect } from 'react';
import { observer } from 'mobx-react';

import { AppContext } from '../App';
import TodoItem from './TodoItem.jsx';

const TodoList = () => {
  const store = useContext(AppContext);

  useEffect(() => {
    store.fetchTodoList();
  }, []);

  return (
    <>
      {store.loading && 'loading..'}
      {store.list.length > 0 && (
        <div className="todo-list">
          {store.list.map((item) => (
            <TodoItem key={item.id} data={item} />
          ))}
        </div>
      )}
    </>
  );
};

export default observer(TodoList);

// todoApp/ui/vueTodoApp/src/components/TodoList.vue
<template>
  <Observer>
    <div v-if="store.loading">loading..</div>
    <div class="todo-list" v-if="store.list.length > 0">
      <div v-for="todo in store.list" :key="todo.id" class="todo">
        <TodoItem :data="todo" />
      </div>
    </div>
  </Observer>
</template>

<script>
import { Observer } from 'mobx-vue-lite';

import TodoItem from './TodoItem.vue';

export default {
  name: 'TodoList',
  components: {
    Observer,
    TodoItem,
  },
  inject: ['store'],
  mounted() {
    this.store.fetchTodoList();
  },
};
</script>
